import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/layout/app-sidebar'
import { AuthProvider, AuthConsumer } from "@/contexts/jwt-context";
import { AuthGuard } from "@/components/auth/auth-guard";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
     <AuthProvider>
          <AuthGuard>
              <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
              {children}
              </SidebarInset>
              </SidebarProvider>
          </AuthGuard>
      </AuthProvider>

      </body>
    </html>
  );
}

